# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46a892751155e0c613a307616aaace4f76413ddedf03e1393515fb49c8ec525cac57e4ffe880c260a2bc684375feec185ea8326eb858811d8a76a19ebb141d5a

test:
  secret_key_base: d1cafc7ee73c29ce60b3dd8443b0bcdd423feca5f2241f520d16696db8fb526a811d65ba66cdc9f7569e58014ee9dd81a00dcc29265d1f60da7011096fdcaa00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
